name: Casos de prueba Telcel

on:
  push:
    branches:
      - DanielaSalgado
  pull_request:
    branches:
      - DanielaSalgado

permissions:
  contents: write   # necesario para publicar en gh-pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Install dependencies
        run: npm install

      - name: Install browsers
        run: npx playwright install chromium

      - name: Run CodeceptJS tests
        run: npx codeceptjs run --features

      # 👉 NUEVO: Generar reporte Allure
      - name: Generate Allure report
        if: always()
        run: |
          npx allure generate output/allure-results --clean -o allure-report || echo "No Allure results found"

      # 👉 NUEVO: Subir artefactos (incluyendo Allure)
      - name: Upload test artifacts (logs, screenshots & allure)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeceptjs-artifacts
          path: |
            output/**
            allure-report/**

      # 👉 NUEVO: Publicar Allure report en GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report