name: Casos de prueba Telcel - Daniela Salgado

# Eventos que activan el workflow
on:
  push:
    branches:
      - DanielaSalgado       # Se ejecuta cuando se hace push en esa rama
  pull_request:
    branches:
      - DanielaSalgado       # Se ejecuta cuando se crea o actualiza un pull request en esa rama

# Permisos necesarios para publicar contenido en GitHub Pages
permissions:
  contents: write            

# Definición del job principal
jobs:
  test:
    runs-on: ubuntu-latest   # Usa una máquina virtual con Ubuntu como sistema operativo

    steps:
      # Paso 1: Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configura Node.js con la versión especificada
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0   # Versión de Node.js que se usará para ejecutar el proyecto

      # Paso 3: Instala las dependencias del proyecto (CodeceptJS, Playwright, etc.)
      - name: Install dependencies
        run: npm install

      # Paso 4: Instala el navegador Chromium para las pruebas con Playwright
      - name: Install browsers
        run: npx playwright install chromium

      # Paso 5: Ejecuta los tests definidos en archivos .feature usando CodeceptJS
      - name: Run CodeceptJS tests
        run: npx codeceptjs run --features
  
      # Paso 6: Genera el reporte Allure desde los resultados de prueba
      - name: Generate Allure report
        if: always()   # Se ejecuta siempre, incluso si los tests fallan
        run: |
          npx allure generate output/allure-results --clean -o allure-report || echo "No Allure results found"

      # Paso 7: Sube los artefactos generados (logs, capturas de pantalla, reporte Allure)
      - name: Upload test artifacts (logs, screenshots & allure)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeceptjs-artifacts
          #Carpeta con resultados de CodeceptJS
          #Carpeta con el reporte visual de Allure
          path: |
            output/**
            allure-report/**

      # Paso 8: Publica el reporte Allure en GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Token de autenticación para publicar
          # Carpeta que se va a publicar
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report   